export default {
  LOADING: 'LOADING',
  ERROR: 'ERROR',
  SET_ORDERSPEC: 'SET_ORDERSPEC',
  SET_INSPECTION_LIST:'SET_INSPECTION_LIST',
  SET_CODE_INFO:'SET_CODE_INFO',
  SET_CURRENT_COUNT:'SET_CURRENT_COUNT',
}
  