export default {
    LOADING: 'LOADING',
    ERROR: 'ERROR',
    SET_GOOD_LIST: 'SET_GOOD_LIST',
    SET_GOOD: 'SET_GOOD',
    SET_GOODS: 'SET_GOODS',
    SET_GOOD_DETAIL_LIST : 'SET_GOOD_DETALI_LIST',
    SET_GOOD_TOTLIST : 'SET_GOOD_TOTLIST',
    SET_CURRENT_PRODUCT_COUNT: 'SET_CURRENT_PRODUCT_COUNT',
    SET_CHECKUP_GOOD: 'SET_CHECKUP_GOOD',
    SET_ALLC_QTY: 'SET_ALLC_QTY',
    SET_PICK_QTY: 'SET_PICK_QTY',
    SET_VALIDPRODUCT: 'SET_VALIDPRODUCT',
    SET_ASSIGNTOTLIST: 'SET_ASSIGNTOTLIST',
    SET_TOTELIST: 'SET_TOTELIST',
    SET_PRODUCT: 'SET_PRODUCT',
    SET_PRODUCT_TARGET: 'SET_PRODUCT_TARGET',
  }
  