const generateState = () => ({
  data: {
    pickList: [],
    pick: {
      deliNo : '',
      deliDiv : '',
      deliDivNm : '',
      status : '',
      statusNm : '',
      deliOrder : '',
      deliDate : '',
      orderCode : '',
      orderId : '',
      orderName : '',
      titleProduct : '',
      productCnt : '',
      qty : '',
      pickQty : '',
      pickerId : '',
      pickerName : '',
      deliMethod : '',
      erpOrderCnt : '',
      erpReserveOrderCnt : '',
      jmProductCnt : '',
      orderRegularYn : '',
    },
    orderCode : '',
    productList:[],
    owner:{},
    totList:[],
    memo : {},
    jobList:[],
    stage:0,
  },
  loading: false,
  error: null,
  groupkey:'',
  hasassigntot:'',
  assignDeliveryinfo:[],
});

export default { ...generateState() };
