export default {
    LOADING: 'LOADING',
    ERROR: 'ERROR',
    SET_ORDERSPEC: 'SET_ORDERSPEC',
    SET_MANUALPICK_LIST:'SET_MANUALPICK_LIST',
    SET_INSPECTION_LIST:'SET_INSPECTION_LIST',
    SET_EVENT_LIST:'SET_EVENT_LIST',
  }
  