export default {
  LOADING: 'LOADING',
  ERROR: 'ERROR',
  AUTH: 'AUTH',
  SET_USERID: 'SET_USERID',
  USERDATA: 'USERDATA',
  OMS_STATUS: 'OMS_STATUS',
  OMS_DELI_DIV: 'OMS_DELI_DIV',
  OMS_DELI_ORDER: 'OMS_DELI_ORDER',
  OMS_DELI_METHOD: 'OMS_DELI_METHOD',
  OMS_PICK_AREA: 'OMS_PICK_AREA',
  SET_STORECODE:'SET_STORECODE',
}
  